spring:
    application:
        name: Jasper-Report
    datasource:
        url: jdbc:postgresql://localhost:5432/practice
        username: postgres
        password: razdeepak
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update  # This can be 'validate', 'update', 'create', or 'create-drop' depending on your needs
        show-sql: true      # Enables logging of SQL statements
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
